# Generated by Django 5.1 on 2024-10-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama_new', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ama_new_data',
            name='Ama_audio_Url',
            field=models.URLField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='ama_new_data',
            name='Ama_response_Url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
