# Generated by Django 5.1 on 2024-09-02 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_a_app_data_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='hod',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
