# Generated by Django 5.1 on 2024-09-02 05:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0008_a_app_data_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_app_data',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
