# Generated by Django 5.1 on 2024-09-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0010_remove_a_app_data_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_app_data',
            name='created_at',
        ),
    ]
