# Generated by Django 5.1 on 2024-09-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0012_alter_a_app_data_response_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='duplicateSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, max_length=100)),
                ('uidi', models.IntegerField(blank=True, db_index=True, null=True)),
                ('otp_verified', models.BooleanField(blank=True, default=False)),
                ('params', models.TextField(blank=True, default='{}')),
                ('remarks', models.TextField(blank=True, default='{}')),
                ('verification_date', models.DateTimeField(auto_now=True)),
                ('send_to_surveyor', models.BooleanField(blank=True, default=False)),
                ('allocated_survey', models.CharField(blank=True, max_length=10, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsef', to='search.project')),
                ('surveyor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responseg', to='search.employee')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsrs', to='search.employee')),
                ('verification_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsee', to='search.verificationstatus')),
            ],
        ),
    ]
