# Generated by Django 5.1 on 2024-12-16 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0014_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDataDump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoints', models.TextField(blank=True, null=True)),
                ('checkpoints_raw', models.TextField(blank=True, null=True)),
                ('uidi', models.IntegerField(blank=True, db_index=True, null=True)),
                ('uid', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('rawdata', models.TextField(blank=True, null=True)),
                ('rawdata_raw', models.TextField(blank=True, null=True)),
                ('image_data', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_app_alldata_to_project', to='search.project')),
            ],
        ),
    ]
