# Generated by Django 5.1 on 2025-01-05 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0016_alter_a_app_data_response_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='a_app_data',
            old_name='date_time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='a_app_data',
            old_name='time',
            new_name='starttime',
        ),
    ]
