# Generated by Django 5.1 on 2025-01-08 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0017_rename_date_time_a_app_data_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frpmdashboard_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='geocodes_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='is_gas_activity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='nccs',
            field=models.BooleanField(default=False),
        ),
    ]
