# Generated by Django 5.1 on 2025-01-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0020_alter_qualityreviewmismatch_interview_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriorityTasksSchedulesID',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False)),
                ('task_created_by', models.CharField(max_length=128)),
                ('task_created_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='A_app_surveyors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_app_id', models.IntegerField(unique=True, verbose_name='a_app_surveyor_id')),
                ('surveyor_name', models.CharField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('emp_id', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surveyor_user', to='search.employee')),
            ],
        ),
    ]
