# Generated by Django 5.1 on 2025-02-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0021_prioritytasksschedulesid_a_app_surveyors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityreview',
            name='interview_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
