# Generated by Django 5.1 on 2026-06-09 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0023_accesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='uid',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
