# Generated by Django 5.2.6 on 2026-08-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0024_alter_surveyresponse_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='response_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
