# Generated by Django 5.2.6 on 2026-08-25 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0025_surveyresponse_response_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='teamleader',
            field=models.CharField(blank=True, db_index=True, max_length=150, null=True),
        ),
    ]
