# Generated by Django 5.2.6 on 2026-08-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0026_surveyresponse_teamleader'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['-verification_date'], name='sr_verification_date_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['project', '-verification_date'], name='sr_project_date_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['surveyor', '-verification_date'], name='sr_surveyor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['user', '-verification_date'], name='sr_user_date_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['verification_status', '-verification_date'], name='sr_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['project', 'surveyor', '-verification_date'], name='sr_project_surveyor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyresponse',
            index=models.Index(fields=['teamleader', '-verification_date'], name='sr_fr_date_idx'),
        ),
    ]
