# Generated by Django 5.1 on 2024-10-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ama_new', '0002_ama_new_data_ama_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ama_new_data',
            name='response_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
