# Generated by Django 5.1 on 2024-08-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='a_app_data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_id', models.IntegerField(blank=True, null=True)),
                ('id1', models.IntegerField(blank=True, null=True)),
                ('surveyor_name', models.CharField(blank=True, max_length=60, null=True)),
                ('surveyor_id', models.IntegerField(blank=True, null=True)),
                ('Respondent_Name', models.CharField(blank=True, max_length=60, null=True)),
                ('question_name', models.CharField(blank=True, max_length=500, null=True)),
                ('question_title', models.CharField(blank=True, max_length=500, null=True)),
                ('Response', models.CharField(blank=True, max_length=500, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=60, null=True)),
                ('survey_name', models.CharField(blank=True, max_length=400, null=True)),
                ('area', models.CharField(blank=True, max_length=60, null=True)),
                ('lat', models.CharField(blank=True, max_length=60, null=True)),
                ('lon', models.CharField(blank=True, max_length=60, null=True)),
                ('audio_recording', models.CharField(blank=True, max_length=40, null=True)),
                ('date_time', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('time', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
