# Generated by Django 5.1 on 2024-09-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0006_alter_department_hod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_app_data',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
