# Generated by Django 5.1 on 2024-09-02 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_a_app_data_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='a_app_data',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
