# Generated by Django 5.1 on 2024-09-02 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0009_alter_a_app_data_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='a_app_data',
            name='updated_at',
        ),
    ]
