# Generated by Django 5.1 on 2024-09-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0011_remove_a_app_data_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_app_data',
            name='Response',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='a_app_data',
            name='question_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
