# Generated by Django 5.1 on 2024-10-11 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0013_duplicatesurveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.project')),
            ],
            options={
                'unique_together': {('employee', 'project')},
            },
        ),
    ]
