# Generated by Django 5.1 on 2025-01-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0015_alldatadump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='a_app_data',
            name='Response',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='a_app_data',
            name='question_title',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
