# Generated by Django 5.1 on 2025-01-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0018_project_frpmdashboard_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityreviewmismatch',
            name='interview_date',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
