# Generated by Django 5.1 on 2025-01-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0019_alter_qualityreviewmismatch_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualityreviewmismatch',
            name='interview_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
